Repository cloudforet-io/inventory, pull requests merged in 2024-05, with the labels that each got.

#279 Refactor Metric Logic
  deploy/helm/Chart.yaml
  src/spaceone/inventory/interface/task/v1/metric_scheduler.py
  src/spaceone/inventory/managed_resource/metric/created_count.yaml
  src/spaceone/inventory/managed_resource/metric/database_count.yaml
  src/spaceone/inventory/managed_resource/metric/deleted_count.yaml
  src/spaceone/inventory/managed_resource/metric/server_count.yaml
  src/spaceone/inventory/managed_resource/metric/storage_size.yaml
  src/spaceone/inventory/manager/metric_manager.py
  src/spaceone/inventory/model/metric/database.py
  src/spaceone/inventory/model/metric/response.py
  src/spaceone/inventory/service/__init__.py
  src/spaceone/inventory/service/metric_service.py
Labels: fail/signedoff

#282 fix: fixed fields for reference type and data type
  src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
  src/spaceone/inventory/plugin/collector/model/field.py
Labels: pass/signedoff

#286 feat: upsert feature of metric and namespace from collector
  src/spaceone/inventory/manager/__init__.py
  src/spaceone/inventory/manager/collecting_manager.py
  src/spaceone/inventory/manager/job_manager.py
  src/spaceone/inventory/manager/metric_manager.py
  src/spaceone/inventory/model/metric/database.py
  src/spaceone/inventory/model/namespace/database.py
Labels: pass/signedoff

#294 Add managed metric yaml for total resource count
  src/spaceone/inventory/managed_resource/metric/total_count.yaml
Labels: enhancement

#297 Change Collector and Cloud Service Model
  src/spaceone/inventory/info/cloud_service_info.py
  src/spaceone/inventory/model/cloud_service_model.py
  src/spaceone/inventory/service/cloud_service_service.py
  src/spaceone/inventory/service/collector_service.py
Labels: pass/signedoff

#304 Refactor Metric Features
  src/spaceone/inventory/manager/metric_data_manager.py
  src/spaceone/inventory/manager/metric_manager.py
  src/spaceone/inventory/model/__init__.py
  src/spaceone/inventory/model/metric/database.py
  src/spaceone/inventory/model/metric_data/database.py
  src/spaceone/inventory/service/metric_service.py
Labels: pass/signedoff

#305 refactor: refactor metric loading process
  src/spaceone/inventory/manager/metric_manager.py
Labels: pass/signedoff

#324 fix: change max length of metric_id
  src/spaceone/inventory/model/metric_data/database.py
Labels: pass/signedoff

#329 refactor: change the logic to run metrics after collecting cloud resources
  src/spaceone/inventory/conf/global_conf.py
  src/spaceone/inventory/manager/job_manager.py
  src/spaceone/inventory/manager/metric_data_manager.py
Labels: pass/signedoff

#332 refactor: add json_data for performance
  src/spaceone/inventory/service/cloud_service_service.py
Labels: pass/signedoff

#333 fix: fix type bug
  src/spaceone/inventory/service/cloud_service_service.py
Labels: pass/signedoff

#356 Refactor Namespace
  src/spaceone/inventory/managed_resource/namespace/asset_change_history.yaml
  src/spaceone/inventory/managed_resource/namespace/asset_summary.yaml
  src/spaceone/inventory/manager/collecting_manager.py
  src/spaceone/inventory/manager/namespace_manager.py
  src/spaceone/inventory/model/metric/request.py
  src/spaceone/inventory/model/namespace/database.py
  src/spaceone/inventory/model/namespace/request.py
  src/spaceone/inventory/model/namespace/response.py
  src/spaceone/inventory/service/metric_service.py
  src/spaceone/inventory/service/namespace_service.py
Labels: pass/signedoff
